### ISSUE TITLE
D9 Readiness

### ISSUE THREAD

**Issue by vuchkov** [ffwagency/vacancy_importer#1]
### Problem / Motivation
- The module is not compatible with Drupal 9.x versions.

### Proposed resolution
- Apply the required changes.

**Comment by vuchkov** [comment]
Resolved in PR: https://github.com/ffwagency/vacancy_importer/pull/2 

@beltofte 
Please review it. (and merge) Thank you.

**Comment by beltofte** [comment]
Merged. Thanks!
